# File to use with Vscode:Extension:REST CLIENT

#Define Var
@HtttApi01=https://api.spotify.com/v1
@HtttApi02=https://accounts.spotify.com
@client_id=6da7c7520c0d443f86ec52e672f98dce
@client_secret=a57cf2a1fdbc4120a93fb609ff8689ee
###
GET {{HtttApi02}}/me
###
GET {{HtttApi01}}/me/playlists
Accept : application/json
Authorization : Bearer BQC65X0d2hco378DBkjKuoR8xmH3056iNZk-0U1ORZAdaW3YgoPvwUuO_STeN810Z39fa7nndByUN7SX441XuBVRrxhqeZAkaeW9iYAF93W8RPoNEs7R7F_ZJQaRZbU5Vg9grjY3eDyJ12Oe6BfeHSRudLSr47y4oqql-uXm7j2G
###
GET {{HtttApi01}}/tracks?ids=7ouMYWpwJ422jRcDASZB7P,4VqPOruhp5EdPBeR92t6lQ,2takcwOaAZWiXQijPHIx7B
Accept : application/json
Authorization : Bearer BQC65X0d2hco378DBkjKuoR8xmH3056iNZk-0U1ORZAdaW3YgoPvwUuO_STeN810Z39fa7nndByUN7SX441XuBVRrxhqeZAkaeW9iYAF93W8RPoNEs7R7F_ZJQaRZbU5Vg9grjY3eDyJ12Oe6BfeHSRudLSr47y4oqql-uXm7j2G
  
###
GET {{HtttApi02}}/api/token
Authorization : Basic a57cf2a1fdbc4120a93fb609ff8689ee
